### ISSUE TITLE
Cannot create clip

### ISSUE THREAD

**Issue by Blake-McCullough** [Durafen/twitch-clip-bot#5]
error i get is:

Traceback (most recent call last):
  File "C:\Users\xxxx\Downloads\twitch-clip-bot-master\twitch-clip-bot-master\twitch-clip-bot.py", line 11, in <module>
    import debug
  File "C:\Users\xxxx\Downloads\twitch-clip-bot-master\twitch-clip-bot-master\debug.py", line 3, in <module>
    import utility
  File "C:\Users\xxxx\Downloads\twitch-clip-bot-master\twitch-clip-bot-master\utility.py", line 14, in <module>
    ROWS, COLUMNS = os.popen('stty size', 'r').read().split()
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by testingapisname** [comment]
Did you ever solve this?
